### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [1]:
import numpy as np

In [2]:
# Creo el array. No se especifica el tipo, ya que int64 es el typo por default con números enteros.
arr1 = np.array ([12,358,7,84,27,128,99,5,389])

In [7]:
#Mostrar el typo de datos
arr1.dtype

dtype('int64')

In [3]:
# muestra la dimensión del array
arr1.ndim

1


In [9]:
# muestra la forma del array
arr1.shape

(9,)

In [6]:
# forma alternativa de crear de array con una función random.
from numpy import random

arr2 = random.randint(100, size=(10))
print (arr2)

[52 26 82 12 89 41  1 25 39 51]


### Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [ ]:
# Cálculo de la media con la función de numpy.
np.mean(arr1) 

In [21]:
# Resta la media de cada valor del array.
arr1 - np.mean(arr1)

array([-111.22222222,  234.77777778, -116.22222222,  -39.22222222,
        -96.22222222,    4.77777778,  -24.22222222, -118.22222222,
        265.77777778])

### Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [39]:
# Creada la matriz bidimensional de forma manual.
arr3 = np.array ([ [1,2,3,4,5],[6,7,8,9,10] ])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [42]:
# Extrae el valor máximo de la matriz (pertenece a la dimensión 0).
np.max(arr3)

10

In [52]:
# Extrae el valor máximo de las dos dimensiones.
arr3.max(axis=1)

array([ 5, 10])

### Exercici 4
Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

### Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

### Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

### Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

### Exercici 8
Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.